version: '3.5'
services:
  app:
    build: .
    container_name: freetunes
    command: npm run dev:docker
    environment:
      - NODE_ENV=development # used to run vite in dev mode with HMR
    ports:
      - '3000:3000'
    volumes:
      - .:/app
